"""refact models

Revision ID: d0f2fb2fa2e5
Revises: af10ab8fa78c
Create Date: 2024-02-21 19:27:46.903008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0f2fb2fa2e5'
down_revision: Union[str, None] = 'af10ab8fa78c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('tg_first_name', sa.String(length=200), nullable=False))
    op.add_column('clients', sa.Column('tg_last_name', sa.String(length=200), nullable=False))
    op.add_column('clients', sa.Column('first_name', sa.String(length=200), nullable=False))
    op.add_column('clients', sa.Column('last_name', sa.String(length=200), nullable=False))
    op.add_column('clients', sa.Column('gender', sa.Enum('male', 'female', 'other', name='genderenum'), nullable=False))
    op.add_column('clients', sa.Column('birth_date', sa.DATE(), nullable=False))
    op.add_column('employees', sa.Column('tg_first_name', sa.String(length=200), nullable=False))
    op.add_column('employees', sa.Column('tg_last_name', sa.String(length=200), nullable=False))
    op.add_column('employees', sa.Column('first_name', sa.String(length=200), nullable=False))
    op.add_column('employees', sa.Column('last_name', sa.String(length=200), nullable=False))
    op.add_column('employees', sa.Column('gender', sa.Enum('male', 'female', 'other', name='genderenum'), nullable=False))
    op.add_column('employees', sa.Column('birth_date', sa.DATE(), nullable=False))
    op.drop_column('users', 'tg_last_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'tg_first_name')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', postgresql.ENUM('male', 'female', 'other', name='genderenum'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('tg_first_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('tg_last_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('employees', 'birth_date')
    op.drop_column('employees', 'gender')
    op.drop_column('employees', 'last_name')
    op.drop_column('employees', 'first_name')
    op.drop_column('employees', 'tg_last_name')
    op.drop_column('employees', 'tg_first_name')
    op.drop_column('clients', 'birth_date')
    op.drop_column('clients', 'gender')
    op.drop_column('clients', 'last_name')
    op.drop_column('clients', 'first_name')
    op.drop_column('clients', 'tg_last_name')
    op.drop_column('clients', 'tg_first_name')
    # ### end Alembic commands ###
